### ISSUE TITLE
数据咨询

### ISSUE THREAD

**Issue by xygroup6** [Hsomething/Urban_Region_Function_Classification#1]
您好，想咨询下“第五届百度西安交大大数据竞赛城市区域功能分类”数据集，请问能方便分享下吗？万分感谢！我叫曾月，今年刚硕士毕业，现在西湖大学做访问学生。我主要研究方向是城市规划，有很多需要学习，尤其是写代码的能力需要快速提高。在Github上看到您“第五届百度西安交大大数据竞赛城市区域功能分类”竞赛的代码。和我的方向很相关，想学习一下您的研究思路，也想跟着练练代码。但是目前我还没有找到比较合适的数据，所以想冒昧请教一下在您方便的前提下，比赛用的数据是否可以分享？仅供我自己初步学习使用，绝不外传。如果您有其他疑问也欢迎可以加我微信核实，我微信是zy18382264487，谢谢！

**Comment by Hsomething** [comment]
这个比赛时间比较久了，我手上的数据因为自己的电脑崩溃而找不回来了，我之前也并没有相应的备份，可能无法帮上您的忙了
